apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: restapi-get
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: MessageGetHandler
    packageref:
      name: restapi-go-pkg
      namespace: default
  requestsPerPod: 1
  resources: {}
