apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: restdelete
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: restapi-delete
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /guestbook/messages/{id:[0-9]+}
    tls: ""
  method: ""
  methods:
  - DELETE
  prefix: ""
  relativeurl: /guestbook/messages/{id:[0-9]+}
