apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: restget
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: restapi-get
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /guestbook/messages/
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /guestbook/messages/
